"""v1_native_ir_consolidated (pass-through)

Revision ID: a11c9ed4a018
Revises: v1_0005_tenant_profile_jobs
Create Date: 2026-04-22

History note
------------
A previous iteration of this revision tried to consolidate the entire v1
schema into a single autogenerated migration rooted at ``down_revision =
None``. That broke the upgrade path for any database already sitting on
``v1_0005_tenant_profile_jobs``. The legacy chain is correct — it
declares TIMESTAMPTZ, server_defaults, and the proper
``case_events_seq`` ``nextval()`` server_default — so the consolidation
was not only unnecessary, it was actively harmful.

This file is now a pass-through sitting directly after v1_0005. It
exists solely to preserve revision continuity for any dev database that
was stamped at ``a11c9ed4a018`` during the broken interval (so
``alembic upgrade head`` doesn't fail with an unknown revision there).
All actual schema is produced by the v1_0001 → v1_0005 chain.
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op  # noqa: F401 — kept for alembic's autogen template
import sqlalchemy as sa  # noqa: F401


revision: str = "a11c9ed4a018"
down_revision: Union[str, Sequence[str], None] = "v1_0005_tenant_profile_jobs"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """No-op: see module docstring."""


def downgrade() -> None:
    """No-op: see module docstring."""
