/**
 * Static ATT&CK lookup (issue #71).
 *
 * Wazuh's `rule.mitre` arrives as three flat, unpaired arrays (ids /
 * tactic names / technique names), so the technique→tactic pairing the
 * evidence rail needs comes from this version-pinned lookup, generated by
 * scripts/gen-attack-lookup.py from the enterprise ATT&CK STIX bundle.
 * Resolution is id-first: wire tactic names are only a fallback for ids
 * the pinned version no longer knows.
 */
import lookup from './attack-lookup.json';

interface LookupTechnique {
	name: string;
	tactics: string[];
	desc: string;
	parent?: string;
	deprecated?: boolean;
}

interface AttackLookup {
	version: string;
	tactics: { id: string; name: string }[];
	techniques: Record<string, LookupTechnique>;
}

const data = lookup as AttackLookup;

export const ATTACK_VERSION: string = data.version;

/** Canonical tactic order from the pinned matrix — the rail's stops. */
export const TACTIC_ORDER: readonly { id: string; name: string }[] = data.tactics;

const TACTIC_NAME_TO_ID = new Map(data.tactics.map((t) => [t.name.toLowerCase(), t.id]));
// Wazuh rule metadata predates ATT&CK renames; map legacy names onto the
// pinned tactics (v19 renamed TA0005 Defense Evasion → Stealth).
const LEGACY_TACTIC_ALIASES = new Map([['defense evasion', 'TA0005']]);

/** Short rail labels — MITRE tactic names are canonical English domain
 * terms, so these are deliberately not localized. */
const TACTIC_ABBREV: Record<string, string> = {
	TA0043: 'Recon',
	TA0042: 'ResDev',
	TA0001: 'Init',
	TA0002: 'Exec',
	TA0003: 'Persist',
	TA0004: 'PrivEsc',
	TA0005: 'Stealth',
	TA0112: 'DefImp',
	TA0006: 'CredAcc',
	TA0007: 'Disc',
	TA0008: 'LatMov',
	TA0009: 'Collect',
	TA0011: 'C2',
	TA0010: 'Exfil',
	TA0040: 'Impact'
};

export function tacticAbbrev(tacticId: string): string {
	return TACTIC_ABBREV[tacticId] ?? tacticId;
}

export function tacticName(tacticId: string): string {
	return data.tactics.find((t) => t.id === tacticId)?.name ?? tacticId;
}

export interface WireMitre {
	ids: string[];
	tactics: string[];
	techniques: string[];
}

export interface ResolvedTechnique {
	id: string;
	name: string;
	desc: string | null;
	/** TA ids; empty when the id is unknown to the pinned version. */
	tactics: string[];
	parentId: string | null;
	parentName: string | null;
	deprecated: boolean;
	/** False when the id was missing from the lookup and the name came
	 * from the wire arrays (or is the bare id). */
	known: boolean;
}

export interface ResolvedMitre {
	techniques: ResolvedTechnique[];
	/** TA id → number of techniques mapped there. */
	tacticCounts: Map<string, number>;
	/** Wire tactic names that matched nothing in the pinned version. */
	unmatchedTactics: string[];
}

export function resolveTechnique(id: string, wireName?: string): ResolvedTechnique {
	const entry = data.techniques[id];
	if (!entry) {
		return {
			id,
			name: wireName || id,
			desc: null,
			tactics: [],
			parentId: null,
			parentName: null,
			deprecated: false,
			known: false
		};
	}
	return {
		id,
		name: entry.name,
		desc: entry.desc || null,
		tactics: entry.tactics,
		parentId: entry.parent ?? null,
		parentName: entry.parent ? (data.techniques[entry.parent]?.name ?? null) : null,
		deprecated: entry.deprecated ?? false,
		known: true
	};
}

/**
 * Resolve one or more wire mitre payloads into deduped techniques plus
 * the rail's tactic activation map. Id-first; wire tactic names cover
 * ids the lookup misses.
 */
export function resolveMitre(wires: (WireMitre | null | undefined)[]): ResolvedMitre {
	const techniques = new Map<string, ResolvedTechnique>();
	const tacticCounts = new Map<string, number>();
	const unmatched = new Set<string>();

	const bump = (ta: string) => tacticCounts.set(ta, (tacticCounts.get(ta) ?? 0) + 1);

	for (const wire of wires) {
		if (!wire) continue;
		const ids = wire.ids ?? [];
		const names = wire.techniques ?? [];
		// Whether THIS wire payload has techniques the lookup couldn't
		// place — computed per wire, not across the accumulated map, so
		// one alert's unknown id never makes another alert's tactic
		// names light rail stops.
		let unplaced = ids.length === 0;
		for (let i = 0; i < ids.length; i++) {
			const id = ids[i];
			if (!id) continue;
			const seen = techniques.get(id);
			if (seen) {
				if (seen.tactics.length === 0) unplaced = true;
				continue;
			}
			// Wazuh emits ids and technique names as parallel arrays; the
			// positional name is only trusted as a label of last resort.
			const positional = ids.length === names.length ? names[i] : undefined;
			const resolved = resolveTechnique(id, positional);
			techniques.set(id, resolved);
			for (const ta of resolved.tactics) bump(ta);
			if (resolved.tactics.length === 0) unplaced = true;
		}
		// Tactic names only matter for techniques the lookup couldn't
		// place (unknown id, or an alert with tactics but no ids).
		if (unplaced) {
			for (const rawName of wire.tactics ?? []) {
				const key = rawName.toLowerCase();
				const ta = TACTIC_NAME_TO_ID.get(key) ?? LEGACY_TACTIC_ALIASES.get(key);
				if (ta) {
					if (!tacticCounts.has(ta)) bump(ta);
				} else {
					unmatched.add(rawName);
				}
			}
		}
	}

	return {
		techniques: [...techniques.values()],
		tacticCounts,
		unmatchedTactics: [...unmatched]
	};
}
